development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_api_demo_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_api_demo_test
  pool: 5
  username: root
  password:

